In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
df = pd.read_csv('churn.csv')
df.head()

,Unnamed: 0,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,Gift Vouchers/Coupons,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0
1,1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,Gift Vouchers/Coupons,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,0
2,2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1
3,3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,1
4,4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,Credit/Debit Card Offers,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,1

In [3]:
df.columns

Index(['Unnamed: 0', 'age', 'gender', 'security_no', 'region_category',
       'membership_category', 'joining_date', 'joined_through_referral',
       'referral_id', 'preferred_offer_types', 'medium_of_operation',
       'internet_option', 'last_visit_time', 'days_since_last_login',
       'avg_time_spent', 'avg_transaction_value', 'avg_frequency_login_days',
       'points_in_wallet', 'used_special_discount',
       'offer_application_preference', 'past_complaint', 'complaint_status',
       'feedback', 'churn_risk_score'],
      dtype='object')

In [4]:
df = df.drop(columns=[c for c in df.columns if c.startswith("Unnamed")])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36992 non-null  object
 2   security_no                   36992 non-null  object
 3   region_category               31564 non-null  object
 4   membership_category           36992 non-null  object
 5   joining_date                  36992 non-null  object
 6   joined_through_referral       36992 non-null  object
 7   referral_id                   36992 non-null  object
 8   preferred_offer_types         36704 non-null  object
 9   medium_of_operation           36992 non-null  object
 10  internet_option               36992 non-null  object
 11  last_visit_time               36992 non-null  object
 12  days_since_last_login         36992 non-null  int64
 13  avg_time_spent                36992 non-null  float64
 14  avg_transaction_value         36992 non-null  float64
 15  avg_frequency_login_days      36992 non-null  object
 16  points_in_wallet              33549 non-null  float64
 17  used_special_discount         36992 non-null  object
 18  offer_application_preference  36992 non-null  object
 19  past_complaint                36992 non-null  object
 20  complaint_status              36992 non-null  object
 21  feedback                      36992 non-null  object
 22  churn_risk_score              36992 non-null  int64
dtypes: float64(3), int64(3), object(17)
memory usage: 6.5+ MB

In [6]:
df['region_category'].unique()

array(['Village', 'City', 'Town', nan], dtype=object)

In [7]:
df['preferred_offer_types'].unique()

array(['Gift Vouchers/Coupons', 'Credit/Debit Card Offers',
       'Without Offers', nan], dtype=object)

In [8]:
# Standardizing placeholder junk value to proper NaN
placeholder_value = ['?', 'xxxxxxxx', 'Unknown', 'unknown', '']
df = df.replace(placeholder_value, np.nan)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36933 non-null  object
 2   security_no                   36992 non-null  object
 3   region_category               31564 non-null  object
 4   membership_category           36992 non-null  object
 5   joining_date                  36992 non-null  object
 6   joined_through_referral       31554 non-null  object
 7   referral_id                   19146 non-null  object
 8   preferred_offer_types         36704 non-null  object
 9   medium_of_operation           31599 non-null  object
 10  internet_option               36992 non-null  object
 11  last_visit_time               36992 non-null  object
 12  days_since_last_login         36992 non-null  int64
 13  avg_time_spent                36992 non-null  float64
 14  avg_transaction_value         36992 non-null  float64
 15  avg_frequency_login_days      36992 non-null  object
 16  points_in_wallet              33549 non-null  float64
 17  used_special_discount         36992 non-null  object
 18  offer_application_preference  36992 non-null  object
 19  past_complaint                36992 non-null  object
 20  complaint_status              36992 non-null  object
 21  feedback                      36992 non-null  object
 22  churn_risk_score              36992 non-null  int64
dtypes: float64(3), int64(3), object(17)
memory usage: 6.5+ MB

In [10]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,NaN,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,NaN,CID21329,Gift Vouchers/Coupons,Desktop,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,0
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,1
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,1

In [11]:
df['avg_frequency_login_days'] = pd.to_numeric(df['avg_frequency_login_days'], errors= 'coerce')

In [12]:
df['joining_date'] = pd.to_datetime(df['joining_date'], errors = 'coerce')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36933 non-null  object
 2   security_no                   36992 non-null  object
 3   region_category               31564 non-null  object
 4   membership_category           36992 non-null  object
 5   joining_date                  36992 non-null  datetime64[ns]
 6   joined_through_referral       31554 non-null  object
 7   referral_id                   19146 non-null  object
 8   preferred_offer_types         36704 non-null  object
 9   medium_of_operation           31599 non-null  object
 10  internet_option               36992 non-null  object
 11  last_visit_time               36992 non-null  object
 12  days_since_last_login         36992 non-null  int64
 13  avg_time_spent                36992 non-null  float64
 14  avg_transaction_value         36992 non-null  float64
 15  avg_frequency_login_days      33470 non-null  float64
 16  points_in_wallet              33549 non-null  float64
 17  used_special_discount         36992 non-null  object
 18  offer_application_preference  36992 non-null  object
 19  past_complaint                36992 non-null  object
 20  complaint_status              36992 non-null  object
 21  feedback                      36992 non-null  object
 22  churn_risk_score              36992 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(3), object(15)
memory usage: 6.5+ MB

In [14]:
# Handling missing values
df['region_category'] = df['region_category'].fillna('Unknown')

In [15]:
df['joined_through_referral'] = df['joined_through_referral'].fillna('Not Specified')

In [16]:
df['preferred_offer_types'] = df['preferred_offer_types'].fillna('No Preference')

In [17]:
df['avg_frequency_login_days'] = df['avg_frequency_login_days'].fillna(df['avg_frequency_login_days'].median())

In [18]:
df['points_in_wallet'] = df['points_in_wallet'].fillna(df['points_in_wallet'].median())

In [19]:
df['medium_of_operation'] = df['medium_of_operation'].fillna('Not Specified')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36933 non-null  object
 2   security_no                   36992 non-null  object
 3   region_category               36992 non-null  object
 4   membership_category           36992 non-null  object
 5   joining_date                  36992 non-null  datetime64[ns]
 6   joined_through_referral       36992 non-null  object
 7   referral_id                   19146 non-null  object
 8   preferred_offer_types         36992 non-null  object
 9   medium_of_operation           36992 non-null  object
 10  internet_option               36992 non-null  object
 11  last_visit_time               36992 non-null  object
 12  days_since_last_login         36992 non-null  int64
 13  avg_time_spent                36992 non-null  float64
 14  avg_transaction_value         36992 non-null  float64
 15  avg_frequency_login_days      36992 non-null  float64
 16  points_in_wallet              36992 non-null  float64
 17  used_special_discount         36992 non-null  object
 18  offer_application_preference  36992 non-null  object
 19  past_complaint                36992 non-null  object
 20  complaint_status              36992 non-null  object
 21  feedback                      36992 non-null  object
 22  churn_risk_score              36992 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(3), object(15)
memory usage: 6.5+ MB

In [21]:
df.head(20)

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,Not Specified,...,300.63,53005.25,17.000000,781.750000,Yes,Yes,No,Not Applicable,Products always in Stock,0
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,Not Specified,CID21329,Gift Vouchers/Coupons,Desktop,...,306.34,12838.38,10.000000,697.620000,Yes,No,Yes,Solved,Quality Customer Care,0
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,516.16,21027.00,22.000000,500.690000,No,Yes,Yes,Solved in Follow-up,Poor Website,1
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,53.27,25239.56,6.000000,567.660000,No,Yes,Yes,Unsolved,Poor Website,1
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,113.13,24483.66,16.000000,663.060000,No,Yes,Yes,Solved,Poor Website,1
5,13,M,PSG1LGF,City,Gold Membership,2016-01-08,No,NaN,Gift Vouchers/Coupons,Not Specified,...,433.62,13884.77,24.000000,722.270000,Yes,No,Yes,Unsolved,No reason specified,0
6,21,M,R3CX1EA,Town,Gold Membership,2015-03-19,Yes,CID24708,Gift Vouchers/Coupons,Desktop,...,55.38,8982.50,28.000000,756.210000,Yes,No,Yes,Solved in Follow-up,No reason specified,0
7,42,M,4UJ1551,Unknown,No Membership,2016-07-12,Not Specified,CID56614,Credit/Debit Card Offers,Both,...,429.11,44554.82,24.000000,568.080000,No,Yes,Yes,Unsolved,Poor Product Quality,1
8,44,M,0481QNQ,Village,Silver Membership,2016-12-14,No,NaN,Without Offers,Smartphone,...,191.07,18362.31,20.000000,697.620000,Yes,No,Yes,Solved in Follow-up,Poor Customer Service,0
9,45,F,ZHP4MCR,Town,No Membership,2016-11-30,No,NaN,Gift Vouchers/Coupons,Not Specified,...,97.31,19244.16,28.000000,706.230000,No,Yes,Yes,No Information Available,Poor Customer Service,1
10,25,F,OKZ6GDD,Village,Basic Membership,2016-05-22,Yes,CID19275,Gift Vouchers/Coupons,Both,...,570.23,35119.93,8.000000,699.700000,Yes,Yes,No,Not Applicable,Poor Product Quality,1
11,60,M,KPI9DD5,City,Gold Membership,2016-01-13,No,NaN,Gift Vouchers/Coupons,Smartphone,...,55.53,41672.02,33.024343,798.120000,Yes,No,No,Not Applicable,Too many ads,0
12,11,M,G2FTZTL,Town,No Membership,2015-01-31,No,NaN,Credit/Debit Card Offers,Smartphone,...,41.09,44007.18,18.000000,608.260000,Yes,No,Yes,Unsolved,Poor Customer Service,1
13,34,M,S71G75R,City,Basic Membership,2016-12-07,Yes,CID10856,Gift Vouchers/Coupons,Smartphone,...,89.76,21318.19,6.000000,697.620000,No,Yes,No,Not Applicable,Poor Product Quality,1
14,40,M,QAL9ZY2,City,Premium Membership,2016-11-19,No,NaN,Without Offers,Not Specified,...,100.59,14842.62,26.000000,697.620000,No,Yes,No,Not Applicable,Poor Website,0
15,16,F,YTBUOEE,Town,Basic Membership,2017-07-09,Not Specified,CID35062,Credit/Debit Card Offers,Smartphone,...,30.14,18792.31,7.000000,141.513201,Yes,No,Yes,Unsolved,Too many ads,1
16,57,F,RZ6TPTR,City,No Membership,2016-01-27,No,NaN,Without Offers,Not Specified,...,333.34,47241.32,8.000000,697.620000,Yes,Yes,Yes,Solved in Follow-up,Too many ads,1
17,11,M,3GHN9RC,Town,Silver Membership,2017-01-02,Yes,CID22930,Gift Vouchers/Coupons,Not Specified,...,275.13,29072.86,26.000000,733.970000,Yes,No,No,Not Applicable,Poor Customer Service,0
18,39,M,DYK6E24,Town,No Membership,2017-11-01,No,NaN,Credit/Debit Card Offers,Smartphone,...,241.74,33170.16,6.000000,551.110000,Yes,No,Yes,No Information Available,No reason specified,1
19,45,M,XYB1CDG,City,Premium Membership,2016-02-03,No,NaN,Without Offers,Not Specified,...,31.15,66982.61,8.000000,164.800769,Yes,No,Yes,Unsolved,Products always in Stock,0

In [22]:
# Removing invalid values -- value shouldn't be in negative
for col in ['avg_time_spent', 'avg_transaction_value', 'points_in_wallet']:
    before = (df[col] < 0).sum()
    if before > 0:
        print(f' fixing {before} negavtive values in {col}')
    df[col] = df[col].clip(lower=0)

 fixing 1719 negavtive values in avg_time_spent
 fixing 136 negavtive values in points_in_wallet

In [23]:
# age sanity check (dropping obiviously invalid ages if any exist)
df = df[(df['age'] >=10) & (df['age'] <=100)]

In [24]:
# Feature engineering - business-relevant derived fields
# Tenure in days/months since joining (reference date = latest joining_date in data as proxy for "today")
reference_date = df['joining_date'].max()
df['tenure_days'] = (reference_date - df['joining_date']).dt.days
df['tenure_month'] = (df['tenure_days'] / 30).round(1)

In [25]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,tenure_days,tenure_month
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,Not Specified,...,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0,136,4.5
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,Not Specified,CID21329,Gift Vouchers/Coupons,Desktop,...,10.0,697.62,Yes,No,Yes,Solved,Quality Customer Care,0,125,4.2
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1,415,13.8
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,1,428,14.3
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,16.0,663.06,No,Yes,Yes,Solved,Poor Website,1,110,3.7

In [26]:
# Revenue at risk = transaction value * churn flag
df['revenue_at_risk'] = np.where(
    df['churn_risk_score'] == 1, df['avg_transaction_value'], 0
)

In [27]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,tenure_days,tenure_month,revenue_at_risk
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,Not Specified,...,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,0,136,4.5,0.00
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,Not Specified,CID21329,Gift Vouchers/Coupons,Desktop,...,697.62,Yes,No,Yes,Solved,Quality Customer Care,0,125,4.2,0.00
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,1,415,13.8,21027.00
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,567.66,No,Yes,Yes,Unsolved,Poor Website,1,428,14.3,25239.56
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,663.06,No,Yes,Yes,Solved,Poor Website,1,110,3.7,24483.66

In [28]:
df['avg_frequency_login_days']

0        17.0
1        10.0
2        22.0
3         6.0
4        16.0
         ...
36987     6.0
36988    28.0
36989    16.0
36990    20.0
36991    16.0
Name: avg_frequency_login_days, Length: 36992, dtype: float64

In [29]:
# Engagement score bucket based on loging frequency
def engagement_bucket(days):
    if pd.isna(days):
        return 'Unknown'
    elif days <= 7:
        return 'Highly Engaged'
    elif days <= 15:
        return 'Moderate Engaged'
    else:
        return 'Low Engaged'

df['engagement_level'] = df['avg_frequency_login_days'].apply(engagement_bucket)

In [30]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,tenure_days,tenure_month,revenue_at_risk,engagement_level
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,Not Specified,...,Yes,Yes,No,Not Applicable,Products always in Stock,0,136,4.5,0.00,Low Engaged
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,Not Specified,CID21329,Gift Vouchers/Coupons,Desktop,...,Yes,No,Yes,Solved,Quality Customer Care,0,125,4.2,0.00,Moderate Engaged
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,No,Yes,Yes,Solved in Follow-up,Poor Website,1,415,13.8,21027.00,Low Engaged
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,No,Yes,Yes,Unsolved,Poor Website,1,428,14.3,25239.56,Highly Engaged
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,No,Yes,Yes,Solved,Poor Website,1,110,3.7,24483.66,Low Engaged

In [31]:
df['membership_category'].unique()

array(['Platinum Membership', 'Premium Membership', 'No Membership',
       'Gold Membership', 'Silver Membership', 'Basic Membership'],
      dtype=object)

In [32]:
# membership tier rank
membership_rank = {
    'No Membership': 0,
    'Basic Membership' : 1,
    'Silver Membership' : 2,
    'Gold Membership' : 3,
    'Premium Membership' : 4,
    'Platinum Membership' : 5
}

df['membership_rank'] = df['membership_category'].map(membership_rank)

In [33]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,tenure_days,tenure_month,revenue_at_risk,engagement_level,membership_rank
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,Not Specified,...,Yes,No,Not Applicable,Products always in Stock,0,136,4.5,0.00,Low Engaged,5
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,Not Specified,CID21329,Gift Vouchers/Coupons,Desktop,...,No,Yes,Solved,Quality Customer Care,0,125,4.2,0.00,Moderate Engaged,4
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,Yes,Yes,Solved in Follow-up,Poor Website,1,415,13.8,21027.00,Low Engaged,0
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,Yes,Yes,Unsolved,Poor Website,1,428,14.3,25239.56,Highly Engaged,0
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,Yes,Yes,Solved,Poor Website,1,110,3.7,24483.66,Low Engaged,0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36933 non-null  object
 2   security_no                   36992 non-null  object
 3   region_category               36992 non-null  object
 4   membership_category           36992 non-null  object
 5   joining_date                  36992 non-null  datetime64[ns]
 6   joined_through_referral       36992 non-null  object
 7   referral_id                   19146 non-null  object
 8   preferred_offer_types         36992 non-null  object
 9   medium_of_operation           36992 non-null  object
 10  internet_option               36992 non-null  object
 11  last_visit_time               36992 non-null  object
 12  days_since_last_login         36992 non-null  int64
 13  avg_time_spent                36992 non-null  float64
 14  avg_transaction_value         36992 non-null  float64
 15  avg_frequency_login_days      36992 non-null  float64
 16  points_in_wallet              36992 non-null  float64
 17  used_special_discount         36992 non-null  object
 18  offer_application_preference  36992 non-null  object
 19  past_complaint                36992 non-null  object
 20  complaint_status              36992 non-null  object
 21  feedback                      36992 non-null  object
 22  churn_risk_score              36992 non-null  int64
 23  tenure_days                   36992 non-null  int64
 24  tenure_month                  36992 non-null  float64
 25  revenue_at_risk               36992 non-null  float64
 26  engagement_level              36992 non-null  object
 27  membership_rank               36992 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(5), object(16)
memory usage: 7.9+ MB

In [35]:
# Complaint flag as boolean
df['has_complaint'] = df['past_complaint'].map({'Yes' : 1, 'No' : 0})

In [36]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,past_complaint,complaint_status,feedback,churn_risk_score,tenure_days,tenure_month,revenue_at_risk,engagement_level,membership_rank,has_complaint
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,Not Specified,...,No,Not Applicable,Products always in Stock,0,136,4.5,0.00,Low Engaged,5,0
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,Not Specified,CID21329,Gift Vouchers/Coupons,Desktop,...,Yes,Solved,Quality Customer Care,0,125,4.2,0.00,Moderate Engaged,4,1
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,Yes,Solved in Follow-up,Poor Website,1,415,13.8,21027.00,Low Engaged,0,1
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,Yes,Unsolved,Poor Website,1,428,14.3,25239.56,Highly Engaged,0,1
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,Yes,Solved,Poor Website,1,110,3.7,24483.66,Low Engaged,0,1

In [37]:
df['feedback'].unique()

array(['Products always in Stock', 'Quality Customer Care',
       'Poor Website', 'No reason specified', 'Poor Product Quality',
       'Poor Customer Service', 'Too many ads', 'User Friendly Website',
       'Reasonable Price'], dtype=object)

In [38]:
# feedback category grouped into positive / negative for quick filtering
negative_feedback = [
    'Poor Website', 'Poor Product Quality', 'Poor Customer Service', 'Too many ads'
]
positive_feedback = [
    'Products always in Stock', 'Quality Customer Care', 'User Friendly Website', 'Reasonable Price'
]

def feedback_sentiment(val):
    if val in negative_feedback:
        return 'Negative'
    elif val in positive_feedback:
        return 'Positive'
    else:
        return 'Neutral'

df['feedback_sentiment'] = df['feedback'].apply(feedback_sentiment)

In [39]:
df.head()

,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,preferred_offer_types,medium_of_operation,...,complaint_status,feedback,churn_risk_score,tenure_days,tenure_month,revenue_at_risk,engagement_level,membership_rank,has_complaint,feedback_sentiment
0,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,NaN,Gift Vouchers/Coupons,Not Specified,...,Not Applicable,Products always in Stock,0,136,4.5,0.00,Low Engaged,5,0,Positive
1,32,F,5K0N3X1,City,Premium Membership,2017-08-28,Not Specified,CID21329,Gift Vouchers/Coupons,Desktop,...,Solved,Quality Customer Care,0,125,4.2,0.00,Moderate Engaged,4,1,Positive
2,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,Gift Vouchers/Coupons,Desktop,...,Solved in Follow-up,Poor Website,1,415,13.8,21027.00,Low Engaged,0,1,Negative
3,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,Gift Vouchers/Coupons,Desktop,...,Unsolved,Poor Website,1,428,14.3,25239.56,Highly Engaged,0,1,Negative
4,31,F,SVZXCWB,City,No Membership,2017-09-12,No,NaN,Credit/Debit Card Offers,Smartphone,...,Solved,Poor Website,1,110,3.7,24483.66,Low Engaged,0,1,Negative

In [40]:
len(df)

36992

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36933 non-null  object
 2   security_no                   36992 non-null  object
 3   region_category               36992 non-null  object
 4   membership_category           36992 non-null  object
 5   joining_date                  36992 non-null  datetime64[ns]
 6   joined_through_referral       36992 non-null  object
 7   referral_id                   19146 non-null  object
 8   preferred_offer_types         36992 non-null  object
 9   medium_of_operation           36992 non-null  object
 10  internet_option               36992 non-null  object
 11  last_visit_time               36992 non-null  object
 12  days_since_last_login         36992 non-null  int64
 13  avg_time_spent                36992 non-null  float64
 14  avg_transaction_value         36992 non-null  float64
 15  avg_frequency_login_days      36992 non-null  float64
 16  points_in_wallet              36992 non-null  float64
 17  used_special_discount         36992 non-null  object
 18  offer_application_preference  36992 non-null  object
 19  past_complaint                36992 non-null  object
 20  complaint_status              36992 non-null  object
 21  feedback                      36992 non-null  object
 22  churn_risk_score              36992 non-null  int64
 23  tenure_days                   36992 non-null  int64
 24  tenure_month                  36992 non-null  float64
 25  revenue_at_risk               36992 non-null  float64
 26  engagement_level              36992 non-null  object
 27  membership_rank               36992 non-null  int64
 28  has_complaint                 36992 non-null  int64
 29  feedback_sentiment            36992 non-null  object
dtypes: datetime64[ns](1), float64(6), int64(6), object(17)
memory usage: 8.5+ MB

In [42]:
# Dropping rows where critical fields are still missing after cleaning
critical_cols = ['age' , 'gender', 'avg_transaction_value' ,'churn_risk_score']
len(df)
df = df.dropna(subset=critical_cols)
len(df)

36933

In [43]:
# Removiing duplicate rows by security no which act as unique key
df = df.drop_duplicates(subset=['security_no'])
len(df)

36933

In [44]:
output_path = 'cleaned_churn.csv'
df.to_csv(output_path, index=False)

In [45]:
print(f"Final shape: {df.shape}")
print(f"\nChurn rate: {df['churn_risk_score'].mean():.1%}")
print(f"\nColumns: {list(df.columns)}")

Final shape: (36933, 30)

Churn rate: 54.1%

Columns: ['age', 'gender', 'security_no', 'region_category', 'membership_category', 'joining_date', 'joined_through_referral', 'referral_id', 'preferred_offer_types', 'medium_of_operation', 'internet_option', 'last_visit_time', 'days_since_last_login', 'avg_time_spent', 'avg_transaction_value', 'avg_frequency_login_days', 'points_in_wallet', 'used_special_discount', 'offer_application_preference', 'past_complaint', 'complaint_status', 'feedback', 'churn_risk_score', 'tenure_days', 'tenure_month', 'revenue_at_risk', 'engagement_level', 'membership_rank', 'has_complaint', 'feedback_sentiment']

In [46]:
!pip install sqlalchemy pymysql pandas

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.52-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: pandas in C:\Users\2025a.LAPTOP\anaconda3\envs\myproject\Lib\site-packages (3.0.3)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.5-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\2025a.LAPTOP\anaconda3\envs\myproject\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\2025a.LAPTOP\anaconda3\envs\myproject\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\2025a.LAPTOP\anaconda3\envs\myproject\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\2025a.LAPTOP\anaconda3\envs\myproject\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\2025a.LAPTOP\anaconda3\envs\myproject\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading sqlalchemy-2.0.52-cp312-cp312-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.2 MB ? eta -:--:--
   --------- ------------------------------ 0.5/2.2 MB 190.7 kB/s eta 0:00:09
   --------- ------------------------------ 0.5/2.2 MB 190.7 kB/s eta 0:00:09
   ------------------- -------------------- 1.0/2.2 MB 359.4 kB/s eta 0:00:04
   ----------------------------- ---------- 1.6/2.2 MB 508.4 kB/s eta 0:00:02
   ---------------------------------------- 2.2/2.2 MB 655.6 kB/s  0:00:03
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Downloading greenlet-3.5.5-cp312-cp312-win_amd64.whl (324 kB)
Installing collected packages: pymysql, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.5.5 pymysql-1.2.0 sqlalchemy-2.0.52

In [47]:
from sqlalchemy import create_engine, text
import pandas as pd

# Update with your actual MySQL credentials
username = "root"
password = "root"
host = "localhost"
port = "3306"
database = "churn_db"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [48]:
df.to_sql(
    "customer_churn",
    engine,
    if_exists="replace",
    index=False,
    chunksize=5000
)
print("Data loaded into MySQL successfully!")

Data loaded into MySQL successfully!